#Get last version kafka
FROM confluentinc/cp-kafka:latest

#Use user "root"
USER root

#Copy and RUN 'create-topic' to create topic in kafka
COPY create-topic.sh /usr/bin/create-topic.sh
RUN chmod +x /usr/bin/create-topic.sh

